"""
    p3p fusion path finder.
    path finder assumes that you have the items to fuse the persona, and that
    you have social links maxed to be able to fuse that arcana's ultimate persona.

    fusions based on these calculators:
    https://arantius.github.io/persona-fusion-calculator/3portable.html?ref=dtf.ru#/list/name
    https://aqiu384.github.io/megaten-fusion-tool/p3p/personas
    ^ base levels + arcanas based on these as well

    fusion chart for reference:
    https://gamefaqs.gamespot.com/psp/971508-shin-megami-tensei-persona-3-portable/map/8014-fusion-chart

"""

# ------------------------------------------------------------------------------

# persona_list -> personas with recipes and results
# persona: {(recipe): result}
persona_list = {

    'abaddon': {('baal zebul', 'lilith', 'pazuzu', 'succubus', 'incubus'): 'beelzebub', ('helel', 'beelzebub', 'satan', 'samael'): 'lucifer', ('nidhoggr', 'attis'): 'satan'},
    'alice': {('titania',): 'abaddon', ('mot', 'samael', 'loa', 'pale rider', 'ghoul'): 'thanatos'},
    'alilat': {('orpheus',): 'lachesis', ('apsaras',): 'titania'},
    'alp': {('angel',): 'ara mitama', ('forneus',): 'berith', ('apsaras', 'orpheus'): 'inugami', ('omoikane',): 'jack frost', ('inugami', 'jack frost'): 'mithra', ('omoikane',): 'naga', ('tam lin',): 'pixie', ('yomotsu shikome', 'apsaras'): 'take minakata', ('angel', 'orpheus'): 'tam lin', ('orpheus',): 'unicorn'},
    'ananta': {('trumpeter'): 'saturnus', ('orpheus'): 'mot'},
    'angel': {('orpheus',): 'alp', ('lilim', 'apsaras'): 'ghoul', ('nekomata', 'pixie'): 'gurr', ('nekomata', 'apsaras'): 'mokoi', ('lilim', 'pixie'): 'neko shogun', ('nekomata',): 'omoikane', ('apsaras', 'pixie'): 'slime', ('alp', 'orpheus'): 'tam lin', ('dominion', 'virtue'): 'throne', ('power', 'principality'): 'virtue'},
    'anubis': {('lucifer',): 'michael', ('seiten taisei',): 'nidhoggr', ('michael',): 'trumpeter'},
    'apsaras': {('orpheus',): 'angel', ('lilim', 'orpheus'): 'eligor', ('nigi mitama',): 'leanan sidhe', ('nekomata', 'angel'): 'mokoi', ('omoikane', 'alp'): 'naga', ('pixie',): 'nekomata', ('kikuri hime', 'parvati'): 'scathach', ('angel', 'pixie'): 'slime', ('yomotsu shikome', 'alp'): 'take minakata'},
    'ara mitama': {('saki mitama', 'kusi mitama', 'mithra', 'nigi mitama'): 'daisoujou', ('orpheus',): 'forneus', ('lilim',): 'inugami', ('nekomata',): 'lilim', ('ares', 'zouchouten'): 'oumitsunu', ('archangel',): 'pyro jack', ('yomotsu shikome', 'omoikane'): 'rakshasa', ('koumokuten', 'nata taishi'): 'thor', ('nekomata', 'orpheus'): 'yatagarasu', ('omoikane', 'pixie'): 'zouchouten'},
    'arahabaki': {('orpheus',): 'ganga', ('pixie',): 'virtue'},
    'archangel': {('pixie',): 'chimera', ('virtue', 'power'): 'dominion', ('throne', 'dominion'): 'melchizedek', ('ara mitama',): 'pyro jack', ('apsaras',): 'tam lin'},
    'ares': {('gurr',): 'empusa', ('nata taishi', 'oumitsunu'): 'koumokuten', ('oberon',): 'lamia', ('mokoi', 'naga'): 'ose', ('zouchouten', 'ara mitama'): 'oumitsunu'},
    'asura': {('ananta',): 'alilat', ('michael',): 'helel', ('messiah', 'helel', 'metatron', 'chi you', 'thanatos'): 'orpheus telos', ('uriel',): 'skadi'},
    'atavaka': {('suparna',): 'skadi', ('pixie',): 'ubelluris'},
    'atropos': {('lachesis', 'clotho'): 'norn', ('chernobog', 'atropos'): 'seiten taisei'},
    'attis': {('chernobog',): 'gabriel', ('kumbhanda', 'pazuzu', 'mot', 'incubus'): 'mara', ('nidhoggr', 'abaddon'): 'satan'},
    'baal zebul': {('abaddon', 'lilith', 'pazuzu', 'succubus', 'incubus'): 'beelzebub', ('attis',): 'mother harlot'},
    'barong': {('kingu', 'forneus'): 'odin', ('kingu', 'oberon'): 'odin', ('rangda',): 'shiva'},
    'beelzebub': {('helel', 'satan', 'abaddon', 'samael'): 'lucifer'},
    'berith': {('thoth', 'flauros'): 'hokuto seikun', ('ara mitama', 'nekomata'): 'legion', ('ares',): 'power', ('fortuna',): 'take mikazuchi', ('valkyrie', 'yomotsu shikome'): 'take mikazuchi'},
    'bishamonten': {('koumokuten', 'jikokuten', 'zouchouten'): 'masakado'},
    'black frost': {('ose', 'orpheus'): 'decarabia', ('loki', 'decarabia', 'ose', 'legion', 'orpheus'): 'susano o', ('titan',): 'vasuki'},
    'byakko': {('suzaku', 'seiryuu', 'genbu'): 'kohryu', ('suzaku', 'nigi mitama'): 'yurlungur'},
    'chernobog': {('seth', 'gurr'): 'baal zebul', ('byakko',): 'hariti', ('kumbhanda', 'atropos'): 'seiten taisei', ('dionysus', 'gurr'): 'seth'},
    'chi you': {('trumpeter',): 'atavaka', ('messiah', 'helel', 'metatron', 'asura', 'thanatos'): 'orpheus telos'},
    'chimera': {('inugami',): 'fortuna', ('unicorn', 'inugami'): 'hua po', ('apsaras',): 'jack frost', ('slime', 'alp'): 'narcissus', ('ares', 'zouchouten'): 'oumitsunu', ('zouchouten', 'tam lin'): 'power', ('unicorn', 'omoikane'): 'shiisaa'},
    'clotho': {('lachesis', 'fortuna'): 'atropos', ('kusi mitama', 'fortuna'): 'lachesis', ('atropos', 'lachesis'): 'norn'},
    'cu chulainn': {('saki mitama', 'taraka'): 'jatayu', ('saki mitama',): 'kaiwan'},
    'cybele': {('pixie',): 'queen mab', ('apsaras',): 'rangda'},
    'daisoujou': {('barong', 'titania'): 'horus', ('pixie'): 'sati'},
    'decarabia': {('narasimha',): 'hecatoncheires', ('ose', 'orpheus'): 'loki', ('ose', 'slime'): 'loki', ('loki', 'ose', 'black frost', 'legion', 'orpheus'): 'susano o'},
    'dionysus': {('kali', 'decarabia'): 'horus', ('chernobog', 'gurr'): 'seth'},
    'dominion': {('throne', 'angel'): 'melchizedek', ('virtue', 'angel'): 'throne'},
    'eligor': {('power',): 'nandi', ('orpheus',): 'yamatano orochi'},
    'empusa': {('king frost', 'setanta'): 'cu chulainn', ('lamia',): 'king frost'},
    'flauros': {('thoth', 'berith'): 'hokuto seikun', ('thoth', 'omoikane'): 'hokuto seikun', ('shiisaa', 'omoikane'): 'thoth'},
    'forneus': {('orpheus',): 'ara mitama', ('kingu', 'raja naga'): 'barong', ('unicorn', 'ara mitama'): 'legion', ('nekomata',): 'nigi mitama', ('omoikane', 'angel'): 'principality', ('king frost', 'take mikazuchi'): 'raja naga'},
    'fortuna': {('lachesis', 'clotho'): 'atropos', ('clotho', 'kusi mitama'): 'lachesis', ('berith',): 'take mikazuchi'},
    'gabriel': {('uriel',): 'baal zebul', ('michael', 'uriel', 'raphael'): 'metatron'},
    'ganesha': {('kaiwan', 'neko shogun'): 'garuda', ('garuda', 'neko shogun'): 'kartikeya'},
    'ganga': {('quetzalcoatl',): 'kaiwan', ('parvati', 'apsaras'): 'kikuri hime', ('sarasvati', 'apsaras'): 'parvati'},
    'garuda': {('ganesha', 'neko shogun'): 'kartikeya', ('horus', 'suzaku', 'yatagarasu', 'gurr'): 'sandalphon'},
    'genbu': {('titan',): 'dionysus', ('byakko', 'suzaku', 'seiryuu'): 'kohryu', ('ares',): 'loa', ('orobas',): 'samael'},
    'ghoul': {('samael', 'loa'): 'mot', ('alice', 'mot', 'samael', 'loa', 'pale rider'): 'thanatos'},
    'girimehkala': {('alice',): 'ganesha', ('orpheus',): 'empusa'},
    'gurr': {('ara mitama', 'nekomata'): 'anubis', ('forneus', 'angel'): 'anubis', ('seth', 'chernobog'): 'baal zebul', ('rangda', 'taraka', 'vetala'): 'girimehkala', ('garuda', 'horus', 'suzaku', 'yatagarasu'): 'sandalphon', ('lilim', 'pixie'): 'uriel'},
    'hanuman': {('titan', 'rakshasa'): 'narasimha', ('orpheus',): 'take minakata'},
    'hariti': {('lilith',): 'cybele', ('orpheus',): 'clotho'},
    'hecatoncheires': {('ubelluris', 'inugami'): 'hell biker', ('ubelluris', 'take minakata'): 'hell biker'},
    'helel': {('beelzebub', 'satan', 'abaddon', 'samael'): 'lucifer', ('messiah', 'metatron', 'chi you', 'asura', 'thanatos'): 'orpheus telos'},
    'hell biker': {('orpheus',): 'orobas', ('pixie',): 'mothman'},
    'high pixie': {('unicorn',): 'apsaras', ('sarasvati', 'high pixie'): 'ganga', ('parvati', 'sarasvati'): 'kikuri hime'},
    'hokuto seikun': {('orpheus',): 'lamia', ('apsaras',): 'oumitsunu'},
    'horus': {('vishnu', 'suparna', 'jatayu', 'quetzalcoatl', 'yatagarasu'): 'asura', ('thanatos', 'norn'): 'chi you', ('garuda', 'suzaku', 'yatagarasu', 'gurr'): 'sandalphon', ('jatayu', 'quetzalcoatl'): 'suparna', ('suparna', 'yatagarasu'): 'vishnu'},
    'hua po': {('virtue',): 'flauros', ('take mikazuchi',): 'genbu', ('sati', 'nekomata'): 'orobas', ('pyro jack', 'nekomata'): 'sati'},
    'incubus': {('baal zebul', 'abaddon', 'lilith', 'pazuzu', 'succubus'): 'beelzebub', ('taraka', 'seiryuu'): 'bishamonten', ('succubus', 'vetala', 'lilim'): 'lilith', ('attis', 'kumbhanda', 'pazuzu', 'mot'): 'mara', ('succubus', 'lilim'): 'pazuzu', ('vetala', 'mokoi'): 'succubus'},
    'inugami': {('ubelluris', 'vasuki', 'orthrus', 'take minakata'): 'attis', ('ara mitama',): 'fortuna', ('jack frost', 'alp'): 'mithra', ('mokoi', 'pyro jack'): 'vetala', ('nigi mitama', 'unicorn'): 'yamatano orochi'},
    'jack frost': {('king frost', 'queen mab', 'pyro jack'): 'black frost', ('inugami', 'alp'): 'mithra', ('angel', 'orpheus'): 'mokoi', ('alp',): 'oberon', ('apsaras', 'pixie'): 'pyro jack'},
    'jatayu': {('vishnu', 'suparna', 'horus', 'quetzalcoatl', 'yatagarasu'): 'asura', ('hokuto seikun',): 'byakko', ('high pixie',): 'mothman', ('horus', 'quetzalcoatl'): 'suparna'},
    'jikokuten': {('titan', 'valkyrie'): 'hanuman', ('bishamonten', 'koumokuten', 'zouchouten'): 'masakado'},
    'kaiwan': {('nandi', 'neko shogun'): 'ganesha', ('ganesha', 'neko shogun'): 'garuda'},
    'kali': {('decarabia', 'dionysus'): 'horus', ('narasimha', 'valkyrie'): 'siegfried'},
    'kartikeya': {('orpheus',): 'uriel', ('pixie',): 'thoth'},
    'kikuri hime': {('okuninushi', 'take minakata', 'omoikane'): 'arahabaki', ('parvati', 'apsaras'): 'scathach'},
    'king frost': {('kingu', 'take mikazuchi'): 'barong', ('queen mab', 'pyro jack', 'jack frost'): 'black frost', ('queen mab', 'pale rider'): 'cu chulainn', ('take mikazuchi', 'forneus'): 'raja naga', ('sati',): 'seiryuu'},
    'kingu': {('raja naga', 'take mikazuchi'): 'barong', ('king frost', 'take mikazuchi'): 'barong', ('barong', 'forneus'): 'odin'},
    'kohryu': {('orpheus',): 'taraka', ('apsaras',): 'nata taishi'},
    'koumokuten': {('vasuki', 'seiryuu'): 'jatayu', ('bishamonten', 'jikokuten', 'zouchouten'): 'masakado', ('nata taishi', 'ara mitama'): 'thor'},
    'kumbhanda': {('attis', 'pazuzu', 'mot', 'incubus'): 'mara', ('chernobog', 'atropos'): 'seiten taisei'},
    'kurama tengu': {('nebiros', 'yomotsu shikome'): 'kumbhanda', ('orpheus',): 'sarasvati'},
    'kusi mitama': {('saki mitama', 'mithra', 'nigi mitama', 'ara mitama'): 'daisoujou', ('clotho', 'fortuna'): 'lachesis'},
    'lachesis': {('clotho', 'fortuna'): 'atropos', ('atropos', 'clotho'): 'norn'},
    'laksmi': {('orpheus',): 'clotho', ('apsaras',): 'saki mitama'},
    'lamia': {('high pixie'): 'jikokuten', ('take minakata'): 'kusi mitama', ('vetala',): 'loa', ('mothman', 'yomotsu shikome'): 'taraka'},
    'leanan sidhe': {('nandi',): 'okuninushi', ('orpheus',): 'empusa'},
    'legion': {('ose', 'slime'): 'decarabia', ('pale rider',): 'jikokuten', ('slime',): 'orpheus', ('narcissus',): 'sarasvati', ('loki', 'decarabia', 'ose', 'black frost', 'orpheus'): 'susano o'},
    'lilim': {('nata taishi', 'narcissus', 'pixie'): 'alice', ('pixie', 'orpheus'): 'eligor', ('apsaras', 'orpheus'): 'eligor', ('succubus', 'incubus', 'vetala'): 'lilith', ('angel', 'pixie'): 'neko shogun', ('gurr', 'pixie'): 'uriel', ('pixie',): 'valkyrie'},
    'lilith': {('baal zebul', 'abaddon', 'pazuzu', 'succubus', 'incubus'): 'beelzebub', ('tam lin',): 'narasimha'},
    'loa': {('setanta', 'empusa'): 'cu chulainn', ('samael', 'ghoul'): 'mot', ('alice', 'mot', 'samael', 'pale rider', 'ghoul'): 'thanatos'},
    'loki': {('decarabia', 'ose', 'black frost', 'legion', 'orpheus'): 'susano o', ('orpheus',): 'legion'},
    'lucifer': {('orpheus',): 'kaiwan', ('angel',): 'uriel'},
    'mara': {('orpheus',): 'dionysus', ('alp',): 'kaiwan'},
    'masakado': {('trumpeter',): 'ananta', ('pixie',): 'nandi'},
    'melchizedek': {('angel',): 'virtue', ('ara mitama',): 'orobas'},
    'messiah': {('helel', 'metatron', 'chi you', 'asura', 'thanatos'): 'orpheus telos'},
    'metatron': {('messiah', 'helel', 'chi you', 'asura', 'thanatos'): 'orpheus telos'},
    'michael': {('seiten taisei',): 'ananta', ('gabriel', 'uriel', 'raphael'): 'metatron', ('anubis',): 'trumpeter'},
    'mithra': {('saki mitama', 'kusi mitama', 'nigi mitama', 'ara mitama'): 'daisoujou', ('pyro jack'): 'pale rider'},
    'mokoi': {('rakshasa',): 'empusa', ('ares', 'naga'): 'ose', ('succubus', 'incubus'): 'pazuzu', ('oberon', 'slime'): 'setanta', ('incubus', 'vetala'): 'succubus', ('pyro jack', 'inugami'): 'vetala'},
    'mot': {('attis', 'kumbhanda', 'pazuzu', 'incubus'): 'mara', ('alice', 'samael', 'loa', 'pale rider', 'ghoul'): 'thanatos'},
    'mother harlot': {('angel',): 'kingu', ('ara mitama',): 'succubus'},
    'mothman': {('lamia', 'yomotsu shikome'): 'taraka', ('lamia', 'naga'): 'taraka'},
    'naga': {('nebiros', 'kuruma tengu'): 'kumbhanda', ('kurama tengu', 'taraka'): 'nebiros', ('ares', 'mokoi'): 'ose', ('oberon',): 'titan'},
    'nandi': {('kaiwan', 'neko shogun'): 'ganesha', ('leanan sidhe',): 'okuninushi'},
    'narasimha': {('kurama tengu',): 'atropos', ('decarabia',): 'hecatoncheires', ('hanuman', 'valkyrie'): 'kali', ('hanuman', 'rakshasa'): 'kali', ('kali', 'valkyrie'): 'siegfried'},
    'narcissus': {('nata taishi', 'lilim', 'pixie'): 'alice', ('tam lin', 'pixie'): 'queen mab', ('tam lin', 'alp'): 'queen mab', ('queen mab', 'pixie'): 'saki mitama', ('legion',): 'sarasvati', ('saki mitama', 'tam lin'): 'titania'},
    'nata taishi': {('naricssus', 'lilim', 'pixie'): 'alice', ('take minakata',): 'clotho', ('oumitsunu', 'ara mitama'): 'koumokuten', ('koumokuten', 'ara mitama'): 'thor'},
    'nebiros': {('kurama tengu', 'yomotsu shikome'): 'kumbhanda', ('kingu',): 'koumokuten'},
    'neko shogun': {('kaiwan', 'nandi'): 'ganesha', ('ganesha', 'kaiwan'): 'garuda', ('garuda', 'neko shogun'): 'kartikeya', ('orpheus',): 'uriel'},
    'nekomata': {('apsaras',): 'alp', ('pixie',): 'forneus', ('angel', 'pixie'): 'gurr', ('ara mitama',): 'lilim', ('forneus',): 'nigi mitama', ('orpheus',): 'omoikane', ('hua po', 'pyro jack'): 'sati', ('rangda', 'orobas'): 'surt', ('ara mitama', 'orpheus'): 'yatagarasu'},
    'nidhoggr': {('jatayu'): 'gabriel', ('abaddon', 'attis'): 'satan'},
    'nigi mitama': {('saki mitama', 'kusi mitama', 'mithra', 'ara mitama'): 'daisoujou', ('apsaras',): 'leanan sidhe', ('inugami', 'ara mitama'): 'narcissus', ('okuninushi', 'seiryuu'): 'suzaku', ('unicorn', 'inugami'): 'yamatano orochi', ('byakko', 'suzaku'): 'yurlungur'},
    'norn': {('scathach', 'uriel'): 'chi you', ('thanatos', 'horus'): 'chi you'},
    'oberon': {('berith',): 'ares', ('raja naga', 'king frost'): 'kingu', ('ares',): 'lamia', ('mokoi', 'slime'): 'setanta', ('naga',): 'titan'},
    'odin': {('quetzalcoatl',): 'laksmi', ('nekomata',): 'seiryuu'},
    'okuninushi': {('kikuri hime', 'take minakata', 'omoikane'): 'arahabaki', ('seiryuu', 'nigi mitama'): 'suzaku'},
    'omoikane': {('ara mitama',): 'archangel', ('kikuri hime', 'okuninushi', 'take minakata'): 'arahabaki', ('inugami', 'ara mitama'): 'high pixie', ('alp', 'apsaras'): 'naga', ('forneus', 'angel'): 'principality', ('yomotsu shikome', 'ara mitama'): 'rakshasa', ('unicorn', 'chimera'): 'shiisaa', ('flauros', 'shiisaa'): 'thoth', ('orpheus',): 'yomotsu shikome', ('ara mitama', 'pixie'): 'zouchouten'},
    'orobas': {('taraka', 'seiryuu'): 'bishamonten', ('sati', 'nekomata'): 'rangda', ('sati', 'jack frost'): 'rangda', ('genbu'): 'samael', ('rangda', 'nekomata'): 'surt'},
    'orpheus': {('ose', 'black frost'): 'decarabia', ('lilim', 'pixie'): 'eligor', ('thanatos',): 'messiah', ('pixie', 'ara mitama'): 'oberon', ('loki', 'decarabia', 'ose', 'black frost', 'legion'): 'susano o', ('alp',): 'unicorn', ('neko shogun',): 'uriel', ('ara mitama', 'nekomata'): 'yatagarasu', ('omoikane',): 'yomotsu shikome'},
    'orpheus telos': {('orpheus',): 'ose', ('pixie',): 'parvati'},
    'orthrus': {('ubelluris', 'vasuki', 'take minakata', 'inugami'): 'attis', ('vetala',): 'dionysus', ('hua po',): 'incubus', ('vasuki', 'take minakata'): 'ubelluris'},
    'ose': {('legion', 'slime'): 'decarabia', ('black frost', 'orpheus'): 'decarabia', ('decarabia', 'orpheus'): 'loki', ('decarabia', 'slime'): 'loki', ('loki', 'decarabia', 'black frost', 'legion', 'orpheus'): 'susano o'},
    'oumitsunu': {('orthrus',): 'clotho', ('nata taishi', 'ara mitama'): 'koumokuten', ('zouchouten', 'ara mitama'): 'nata taishi', ('zouchouten', 'chimera'): 'nata taishi'},
    'pale rider': {('king frost', 'queen mab'): 'cu chulainn', ('black frost',): 'hanuman', ('alice', 'mot', 'samael', 'loa', 'ghoul'): 'thanatos'},
    'parvati': {('sarasvati', 'high pixie'): 'kikuri hime', ('kikuri hime', 'apsaras'): 'scathach'},
    'pazuzu': {('baal zebul', 'abaddon', 'lilith', 'succubus', 'incubus'): 'beelzebub', ('attis', 'kumbhanda', 'mot', 'incubus'): 'mara'},
    'pixie': {('nata taishi', 'narcissus', 'lilim'): 'alice', ('yomotsu shikome',): 'archangel', ('raphael', 'titania'): 'cybele', ('lilim', 'orpheus'): 'eligor', ('lilim', 'angel'): 'neko shogun', ('apsaras',): 'nekomata', ('angel', 'apsaras'): 'slime', ('gurr', 'lilim'): 'uriel', ('lilim',): 'valkyrie', ('omoikane', 'ara mitama'): 'zouchouten'},
    'power': {('virtue', 'angel'): 'dominion', ('virtue', 'archangel'): 'dominion', ('principality', 'angel'): 'virtue'},
    'principality': {('archangel',): 'angel', ('berith',): 'ares', ('power', 'angel'): 'virtue'},
    'pyro jack': {('king frost', 'queen mab', 'jack frost'): 'black frost', ('mithra',): 'pale rider', ('hua po', 'nekomata'): 'sati', ('mokoi', 'inugami'): 'vetala'},
    'queen mab': {('king frost', 'pyro jack', 'jack frost'): 'black frost', ('king frost', 'pale rider'): 'cu chulainn', ('narcissus', 'pixie'): 'saki mitama', ('narcissus', 'alp'): 'saki mitama'},
    'quetzalcoatl': {('vishnu', 'suparna', 'horus', 'jatayu', 'quetzalcoatl'): 'asura', ('odin',): 'laksmi'},
    'raja naga': {('kingu', 'forneus'): 'barong', ('king frost', 'forneus'): 'kingu', ('king frost', 'oberon'): 'kingu', ('yatagarasu',): 'yaksini'},
    'rakshasa': {('narasimha', 'hanuman'): 'kali', ('hanuman', 'titan'): 'narasimha', ('yamatano orochi',): 'orthrus'},
    'rangda': {('taraka', 'vetala', 'gurr'): 'girimehkala', ('barong',): 'shiva', ('orobas', 'nekomata'): 'surt'},
    'raphael': {('titania', 'pixie'): 'cybele', ('micahel', 'gabriel', 'uriel'): 'metatron'},
    'saki mitama': {('kusi mitama', 'mithra', 'nigi mitama', 'ara mitama'): 'daisoujou', ('cu chulainn', 'taraka'): 'jatayu', ('titania', 'pixie'): 'raphael', ('narcissus', 'tam lin'): 'titania'},
    'samael': {('helel', 'beelzebub', 'satan', 'abaddon', 'samael'): 'lucifer', ('loa', 'ghoul'): 'mot', ('alice', 'mot', 'loa', 'pale rider', 'ghoul'): 'thanatos'},
    'sandalphon': {('apsaras',): 'nandi', ('omoikane',): 'okuninushi'},
    'sarasvati': {('unicorn',): 'apsaras', ('high pixie', 'apsaras'): 'ganga', ('high pixie', 'unicorn'): 'ganga', ('ganga', 'apsaras'): 'parvati'},
    'satan': {('masakado',): 'atavaka', ('vishnu',): 'helel', ('helel', 'beelzebub', 'abaddon', 'samael'): 'lucifer'},
    'sati': {('power',): 'flauros', ('narcissus',): 'king frost', ('pyro jack', 'jack frost'): 'orobas', ('hua po', 'nekomata'): 'orobas', ('orobas', 'nekomata'): 'rangda', ('king frost',): 'seiryuu'},
    'saturnus': {('raphael',): 'shiva', ('trumpeter',): 'ananta'},
    'scathach': {('uriel', 'norn'): 'chi you', ('orpheus',): 'dominion'},
    'seiryuu': {('taraka', 'orobas'): 'bishamonten', ('taraka', 'incubus'): 'bishamonten', ('byakko', 'suzaku', 'genbu'): 'kohryu', ('okuninushi', 'nigi mitama'): 'suzaku'},
    'seiten taisei': {('anubis',): 'nidhoggr', ('orpheus',): 'dionysus'},
    'setanta': {('ganesha', 'kaiwan'): 'neko shogun', ('shiisaa', 'take mikazuchi'): 'quetzalcoatl'},
    'seth': {('chernobog', 'gurr'): 'baal zebul', ('scathach',): 'kartikeya'},
    'shiisaa': {('setanta', 'take mikazuchi'): 'quetzalcoatl', ('flauros', 'omoikane'): 'thoth'},
    'shiva': {('omoikane',): 'suzaku', ('nigi mitama',): 'pazuzu'},
    'siegfried': {('orpheus',): 'vasuki', ('angel',): 'seiryuu'},
    'skadi': {('mother harlot', 'yaksini'): 'alilat', ('nekomata',): 'ubelluris'},
    'slime': {('ose', 'legion'): 'decarabia', ('chimera', 'alp'): 'narcissus', ('legion',): 'orpheus', ('mokoi', 'oberon'): 'setanta'},
    'succubus': {('baal zebul', 'abaddon', 'lilith', 'pazuzu', 'incubus'): 'beelzebub', ('incubus', 'vetala', 'lilim'): 'lilith', ('incubus', 'mokoi'): 'pazuzu'},
    'suparna': {('vishnu', 'horus', 'jatayu', 'quetzalcoatl', 'yatagarasu'): 'asura', ('horus', 'yatagarasu'): 'vishnu'},
    'surt': {('thor',): 'abaddon', ('pixie',): 'king frost'},
    'susano o': {('orpheus',): 'legion', ('angel',): 'titania'},
    'suzaku': {('narasimha',): 'chernobog', ('byakko', 'seiryuu', 'genbu'): 'kohryu', ('garuda', 'horus', 'yatagarasu', 'gurr'): 'sandalphon', ('byakko', 'nigi mitama'): 'yurlungur'},
    'take mikazuchi': {('kingu', 'king frost'): 'barong', ('power',): 'incubus', ('setanta', 'shiisaa'): 'quetzalcoatl', ('king frost', 'forneus'): 'raja naga'},
    'take minakata': {('kikuri hime', 'okuninushi', 'omoikane'): 'arahabaki', ('ubelluris', 'vasuki', 'orthrus', 'inugami'): 'attis', ('vasuki', 'orthrus'): 'ubelluris'},
    'tam lin': {('alp',): 'pixie', ('zouchouten', 'chimera'): 'power', ('narcissus', 'pixie'): 'queen mab', ('saki mitama', 'narcissus'): 'titania'},
    'taraka': {('seiryuu', 'orobas'): 'bishamonten', ('seiryuu', 'incubus'): 'bishamonten', ('rangda', 'vetala', 'gurr'): 'girimehkala', ('kurama tengu', 'yomotsu shikome'): 'nebiros'},
    'thanatos': {('horus', 'norn'): 'chi you', ('orpheus',): 'messiah', ('messiah', 'helel', 'metatron', 'chi you', 'asura'): 'orpheus telos'},
    'thor': {('nebiros',): 'byakko', ('orpheus',): 'king frost'},
    'thoth': {('flauros', 'omoikane'): 'hokuto seikun', ('orpheus',): 'lamia'},
    'throne': {('mot',): 'chernobog', ('dominion', 'angel'): 'melchizedek'},
    'titan': {('jikokuten', 'valkyrie'): 'hanuman', ('vetala',): 'kusi mitama', ('sarasvati',): 'mothman', ('black frost',): 'vasuki'},
    'titania': {('raphael', 'pixie'): 'cybele', ('seth',): 'hariti', ('saki mitama',): 'raphael', ('saki mitama', 'alp'): 'raphael'},
    'trumpeter': {('satan',): 'michael', ('ananta',): 'saturnus'},
    'ubelluris': {('vasuki', 'orthrus', 'take minakata', 'inugami'): 'attis', ('vasuki', 'inugami'): 'hecatoncheires'},
    'unicorn': {('sarasvati', 'high pixie'): 'ganga', ('inugami', 'chimera'): 'hua po', ('forneus', 'ara mitama'): 'legion', ('ganga', 'apsaras'): 'parvati', ('chimera', 'omoikane'): 'shiisaa', ('nigi mitama', 'inugami'): 'yamatano orochi'},
    'uriel': {('scathach', 'norn'): 'chi you', ('michael', 'gabriel', 'raphael'): 'metatron'},
    'valkyrie': {('alp',): 'berith', ('jikokuten', 'titan'): 'hanuman', ('hanuman', 'jikokuten'): 'narasimha', ('chimera',): 'principality', ('kali', 'narasimha'): 'siegfried'},
    'vasuki': {('ubelluris', 'orthrus', 'take minakata', 'inugami'): 'attis', ('ubelluris', 'inugami'): 'hecatoncheires', ('orthrus', 'take minakata'): 'ubelluris'},
    'vetala': {('hua po',): 'genbu', ('rangda', 'taraka', 'gurr'): 'girimehkala', ('succubus', 'incubus', 'lilim'): 'lilith', ('incubus', 'mokoi'): 'succubus'},
    'virtue': {('power', 'angel'): 'dominion', ('power', 'archangel'): 'dominion', ('dominion', 'angel'): 'throne'},
    'vishnu': {('suparna', 'horus', 'jatayu', 'quetzalcoatl', 'yatagarasu'): 'asura', ('horus',): 'suparna'},
    'yaksini': {('orpheus',): 'kusi mitama', ('nekomata',): 'orthrus'},
    'yamatano orochi': {('loa', 'pale rider'): 'cu chulainn', ('rakshasa',): 'orthrus', ('chernobog', 'dionysus'): 'seth'},
    'yatagarasu': {('sarasvati',): 'nandi', ('garuda', 'horus', 'suzaku', 'gurr'): 'sandalphon', ('suparna', 'horus'): 'vishnu', ('raja naga',): 'yaksini'},
    'yomotsu shikome': {('omoikane',): 'chimera', ('lilim',): 'ghoul', ('inugami', 'pixie'): 'high pixie', ('kurama tengu', 'taraka'): 'nebiros', ('omoikane', 'ara mitama'): 'rakshasa', ('alp', 'apsaras'): 'take minakata'},
    'yurlungur': {('sandalphon',): 'mother harlot', ('jack frost',): 'samael'},
    'zouchouten': {('nata taishi', 'oumitsunu'): 'koumokuten', ('bishamonten', 'koumokuten', 'jikokuten'): 'masakado', ('oumitsunu', 'ara mitama'): 'nata taishi', ('tam lin', 'chimera'): 'power'},

}

# ------------------------------------------------------------------------------

# persona_stats -> dict with base levels + arcana
# persona: (base level, arcana)
persona_stats = {

    'abaddon': (68, 'devil'),
    'alice': (56, 'death'),
    'alilat': (84, 'empress'),
    'alp': (6, 'lovers'),
    'ananta': (75, 'aeon'),
    'angel': (4, 'angel'),
    'anubis': (59, 'justice'),
    'apsaras': (3, 'priestess'),
    'ara mitama': (6, 'chariot'),
    'arahabaki': (60, 'hermit'),
    'archangel': (10, 'justice'),
    'ares': (19, 'chariot'),
    'asura': (85, 'sun'),
    'atavaka': (80, 'aeon'),
    'atropos': (54, 'fortune'),
    'attis': (67, 'hanged man'),
    'baal zebul': (71, 'moon'),
    'barong': (52, 'emperor'),
    'beelzebub': (81, 'devil'),
    'berith': (13, 'hierophant'),
    'bishamonten': (60, 'tower'),
    'black frost': (34, 'fool'),
    'byakko': (57, 'temperance'),
    'chernobog': (58, 'moon'),
    'chi you': (86, 'tower'),
    'chimera': (9, 'chariot'),
    'clotho': (38, 'fortune'),
    'cu chulainn': (40, 'tower'),
    'cybele': (60, 'lovers'),
    'daisoujou': (53, 'hierophant'),
    'decarabia': (50, 'fool'),
    'dionysus': (48, 'moon'),
    'dominion': (42, 'justice'),
    'eligor': (31, 'tower'),
    'empusa': (23, 'fortune'),
    'flauros': (33, 'hierophant'),
    'forneus': (7, 'emperor'),
    'fortuna': (17, 'fortune'),
    'gabriel': (69, 'empress'),
    'ganesha': (58, 'star'),
    'ganga': (35, 'priestess'),
    'garuda': (65, 'star'),
    'genbu': (29, 'temperance'),
    'ghoul': (18, 'death'),
    'girimehkala': (42, 'moon'),
    'gurr': (15, 'moon'),
    'hanuman': (37, 'strength'),
    'hariti': (62, 'empress'),
    'hecatoncheires': (54, 'hanged man'),
    'helel': (88, 'star'),
    'hell biker': (60, 'hanged man'),
    'high pixie': (21, 'priestess'),
    'hokuto seikun': (47, 'hierophant'),
    'horus': (63, 'sun'),
    'hua po': (20, 'magician'),
    'incubus': (34, 'devil'),
    'inugami': (10, 'hanged man'),
    'jack frost': (8, 'magician'),
    'jatayu': (55, 'sun'),
    'jikokuten': (29, 'strength'),
    'kaiwan': (49, 'star'),
    'kali': (55, 'strength'),
    'kartikeya': (70, 'star'),
    'kikuri hime': (53, 'priestess'),
    'king frost': (30, 'emperor'),
    'kingu': (46, 'emperor'),
    'kohryu': (66, 'hierophant'),
    'koumokuten': (43, 'chariot'),
    'kumbhanda': (56, 'hermit'),
    'kurama tengu': (44, 'hermit'),
    'kusi mitama': (29, 'fortune'),
    'lachesis': (45, 'fortune'),
    'laksmi': (57, 'empress'),
    'lamia': (25, 'hermit'),
    'leanan sidhe': (33, 'empress'),
    'legion': (22, 'fool'),
    'lilim': (8, 'devil'),
    'lilith': (61, 'devil'),
    'loa': (31, 'death'),
    'loki': (58, 'fool'),
    'lucifer': (89, 'judgment'),
    'mara': (77, 'tower'),
    'masakado': (73, 'tower'),
    'melchizedek': (59, 'justice'),
    'messiah': (90, 'judgment'),
    'metatron': (89, 'aeon'),
    'michael': (72, 'judgment'),
    'mithra': (22, 'temperance'),
    'mokoi': (18, 'devil'),
    'mot': (45, 'death'),
    'mother harlot': (74, 'empress'),
    'mothman': (32, 'hermit'),
    'naga': (17, 'hermit'),
    'nandi': (39, 'star'),
    'narasimha': (46, 'strength'),
    'narcissus': (20, 'lovers'),
    'nata taishi': (37, 'chariot'),
    'nebiros': (50, 'hermit'),
    'neko shogun': (19, 'star'),
    'nekomata': (5, 'magician'),
    'nidhoggr': (69, 'aeon'),
    'nigi mitama': (12, 'temperance'),
    'norn': (62, 'fortune'),
    'oberon': (15, 'emperor'),
    'odin': (57, 'emperor'),
    'okuninushi': (44, 'temperance'),
    'omoikane': (7, 'hierophant'),
    'orobas': (34, 'magician'),
    'orpheus': (1, 'fool'),
    'orpheus telos': (1, 'fool'),
    'orthrus': (28, 'hanged man'),
    'ose': (44, 'fool'),
    'oumitsunu': (30, 'chariot'),
    'pale rider': (24, 'death'),
    'parvati': (47, 'priestess'),
    'pazuzu': (52, 'devil'),
    'pixie': (2, 'lovers'),
    'power': (25, 'justice'),
    'principality': (16, 'justice'),
    'pyro jack': (14, 'magician'),
    'queen mab': (27, 'lovers'),
    'quetzalcoatl': (43, 'sun'),
    'raja naga': (36, 'emperor'),
    'rakshasa': (16, 'strength'),
    'rangda': (40, 'magician'),
    'raphael': (61, 'lovers'),
    'saki mitama': (39, 'lovers'),
    'samael': (37, 'death'),
    'sandalphon': (74, 'moon'),
    'sarasvati': (27, 'priestess'),
    'satan': (79, 'judgment'),
    'sati': (28, 'magician'),
    'saturnus': (78, 'star'),
    'scathach': (64, 'priestess'),
    'seiryuu': (36, 'temperance'),
    'seiten taisei': (67, 'tower'),
    'setanta': (28, 'star'),
    'seth': (66, 'moon'),
    'shiisaa': (26, 'hierophant'),
    'shiva': (82, 'tower'),
    'siegfried': (59, 'strength'),
    'skadi': (80, 'empress'),
    'slime': (12, 'fool'),
    'succubus': (43, 'devil'),
    'suparna': (70, 'sun'),
    'surt': (52, 'magician'),
    'susano o': (76, 'fool'),
    'suzaku': (51, 'temperance'),
    'take mikazuchi': (24, 'emperor'),
    'take minakata': (21, 'hanged man'),
    'tam lin': (13, 'lovers'),
    'taraka': (38, 'hermit'),
    'thanatos': (64, 'death'),
    'thor': (53, 'chariot'),
    'thoth': (41, 'hierophant'),
    'throne': (51, 'justice'),
    'titan': (23, 'strength'),
    'titania': (48, 'lovers'),
    'trumpeter': (65, 'judgment'),
    'ubelluris': (48, 'hanged man'),
    'unicorn': (11, 'priestess'),
    'uriel': (63, 'aeon'),
    'valkyrie': (11, 'strength'),
    'vasuki': (38, 'hanged man'),
    'vetala': (24, 'devil'),
    'virtue': (32, 'justice'),
    'vishnu': (78, 'sun'),
    'yaksini': (50, 'empress'),
    'yamatano orochi': (26, 'moon'),
    'yatagarasu': (30, 'sun'),
    'yomotsu shikome': (9, 'hermit'),
    'yurlungur': (64, 'temperance'),
    'zouchouten': (14, 'chariot')

}
