"""
    p3p fusion path finder.
    path finder assumes that you have the items to fuse the persona, and that
    you have social links maxed to be able to fuse that arcana's ultimate persona.
    fusions based on these calculators:
    https://arantius.github.io/persona-fusion-calculator/3portable.html?ref=dtf.ru#/list/name
    https://aqiu384.github.io/megaten-fusion-tool/p3p/personas
    -> try for 2 forward fusions each persona bc using dictionaries
    -> make sure to check special recipe fusions and add them

    add comma to tuples with only one var
    STOPPED AT CHI YOU

"""

# ------------------------------------------------------------------------------

"""
    initial dict setup
    persona_name: {
        {(recipes): resulting persona}
        -> recipes is a tuple (for fusions 3+)
    }
"""

# name = persona_list['ose'] -> finding persona in dict
# for i in name:
#    print(i) -> gets key names in tuple
#    print(name[str(i)]) -> gets resulting persona

persona_list = {

    'abaddon': {('baal zebul', 'lilith', 'pazuzu', 'succubus', 'incubus'): 'beelzebub', ('helel', 'beelzebub', 'satan', 'samael'): 'lucifer', ('nidhoggr', 'attis'): 'satan'},
    'alice': {('titania'): 'abaddon', ('mot', 'samael', 'loa', 'pale rider', 'ghoul'): 'thanatos'},
    'alilat': {('orpheus'): 'lachesis', ('apsaras'): 'titania'},
    'alp': {('angel'): 'ara mitama', ('forneus'): 'berith', ('apsaras', 'orpheus'): 'inugami', ('omoikane'): 'jack frost', ('inugami', 'jack frost'): 'mithra', ('omoikane'): 'naga', ('tam lin'): 'pixie', ('yomotsu shikome', 'apsaras'): 'take minakata', ('angel', 'orpheus'): 'tam lin', ('orpheus'): 'unicorn'},
    'ananta': {('trumpeter'): 'saturnus', ('orpheus'): 'mot'},
    'angel': {('orpheus'): 'alp', ('lilim', 'apsaras'): 'ghoul', ('nekomata', 'pixie'): 'gurr', ('nekomata', 'apsaras'): 'mokoi', ('lilim', 'pixie'): 'neko shogun', ('nekomata'): 'omoikane', ('apsaras', 'pixie'): 'slime', ('alp', 'orpheus'): 'tam lin', ('dominion', 'virtue'): 'throne', ('power', 'principality'): 'virtue'},
    'anubis': {('lucifer'): 'michael', ('seiten taisei'): 'nidhoggr', ('michael'): 'trumpeter'},
    'apsaras': {('orpheus'): 'angel', ('lilim', 'orpheus'): 'eligor', ('nigi mitama'): 'leanan sidhe', ('nekomata', 'angel'): 'mokoi', ('omoikane', 'alp'): 'naga', ('pixie'): 'nekomata', ('kikuri hime', 'parvati'): 'scathach', ('angel', 'pixie'): 'slime', ('yomotsu shikome', 'alp'): 'take minakata'},
    'ara mitama': {('saki mitama', 'kusi mitama', 'mithra', 'nigi mitama'): 'daisoujou', ('orpheus'): 'forneus', ('lilim'): 'inugami', ('nekomata'): 'lilim', ('ares', 'zouchouten'): 'oumitsunu', ('archangel'): 'pyro jack', ('yomotsu shikome', 'omoikane'): 'rakshasa', ('koumokuten', 'nata taishi'): 'thor', ('nekomata', 'orpheus'): 'yatagarasu', ('omoikane', 'pixie'): 'zouchouten'},
    'arahabaki': {('orpheus'): 'ganga', ('pixie'): 'virtue'},
    'archangel': {('pixie'): 'chimera', ('virtue', 'power'): 'dominion', ('throne', 'dominion'): 'melchizedek', ('ara mitama'): 'pyro jack', ('apsaras'): 'tam lin'},
    'ares': {('gurr'): 'empusa', ('nata taishi', 'oumitsunu'): 'koumokuten', ('oberon'): 'lamia', ('mokoi', 'naga'): 'ose', ('zouchouten', 'ara mitama'): 'oumitsunu'},
    'asura': {('ananta'): 'alilat', ('michael'): 'helel', ('messiah', 'helel', 'metatron', 'chi you', 'thanatos'): 'orpheus telos', ('uriel'): 'skadi'},
    'atavaka': {('suparna'): 'skadi', ('pixie'): 'ubelluris'},
    'atropos': {('lachesis', 'clotho'): 'norn', ('chernobog', 'atropos'): 'seiten taisei'},
    'attis': {('chernobog'): 'gabriel', ('kumbhanda', 'pazuzu', 'mot', 'incubus'): 'mara', ('nidhoggr', 'abaddon'): 'satan'},
    'baal zebul': {('abaddon', 'lilith', 'pazuzu', 'succubus', 'incubus'): 'beelzebub', ('attis'): 'mother harlot'},
    'barong': {('kingu', 'forneus'): 'odin', ('kingu', 'oberon'): 'odin', ('rangda'): 'shiva'},
    'beelzebub': {('helel', 'satan', 'abaddon', 'samael'): 'lucifer'},
    'berith': {('thoth', 'flauros'): 'hokuto seikun', ('ara mitama', 'nekomata'): 'legion', ('ares'): 'power', ('fortuna'): 'take mikazuchi', ('valkyrie', 'yomotsu shikome'): 'take mikazuchi'},
    'bishamonten': {('koumokuten', 'jikokuten', 'zouchouten'): 'masakado'},
    'black frost': {('ose', 'orpheus'): 'decarabia', ('loki', 'decabaria', 'ose', 'legion', 'orpheus'): 'susano o', ('titan'): 'vasuki'},
    'byakko': {('suzaku', 'seiryuu', 'genbu'): 'kohryu', ('suzaku', 'nigi mitama'): 'yurlungur'},
    'chernobog': {('seth', 'gurr'): 'baal zebul', ('byakko'): 'hariti', ('kumbhanda', 'atropos'): 'seiten taisei', ('dionysus', 'gurr'): 'seth'},
    'chi you': {('trumpeter'): 'atavaka', ('messiah', 'helel', 'metatron', 'asura', 'thanatos'): 'orpheus telos'},
    'chimera': {('inugami'): 'fortuna', ('unicorn', 'inugami'): 'hua po', ('apsaras'): 'jack frost', ('slime', 'alp'): 'narcissus', ('ares', 'zouchouten'): 'oumitsunu', ('zouchouten', 'tam lin'): 'power', ('unicorn', 'omoikane'): 'shiisaa'},
    'clotho': {('lachesis', 'fortuna'): 'atropos', ('kusi mitama', 'fortuna'): 'lachesis', ('atropos', 'lachesis'): 'norn'},
    'cu chulainn': {('saki mitama', 'taraka'): 'jatayu', ('saki mitama'): 'kaiwan'},
    'cybele': {('pixie'): 'queen mab', ('apsaras'): 'rangda'},
    'daisoujou': {('barong', 'titania'): 'horus', ('pixie'): 'sati'},
    'decarabia': {('narasimha'): 'hecatoncheires', ('ose', 'orpheus'): 'loki', ('ose', 'slime'): 'loki', ('loki', 'ose', 'black frost', 'legion', 'orpheus'): 'susano o'},
    'dionysus': {('kali', 'decarabia'): 'horus', ('chernobog', 'gurr'): 'seth'},
    'dominion': {('throne', 'angel'): 'melchizedek', ('virtue', 'angel'): 'throne'},
    'eligor': {('power'): 'nandi', ('orpheus'): 'yamatano orochi'},
    'empusa': {('king frost', 'setanta'): 'cu chulainn', ('lamia'): 'king frost'},
    'flauros': {('thoth', 'berith'): 'hokuto seikun', ('thoth', 'omoikane'): 'hokuto seikun', ('shiisaa', 'omoikane'): 'thoth'},
    'forneus': {('orpheus'): 'ara mitama', ('kingu', 'raja naga'): 'barong', ('unicorn', 'ara mitama'): 'legion', ('nekomata'): 'nigi mitama', ('omoikane', 'angel'): 'principality', ('king frost', 'take mikazuchi'): 'raja naga'},
    'fortuna': {('lachesis', 'clotho'): 'atropos', ('clotho', 'kusi mitama'): 'lachesis', ('berith'): 'take mikazuchi'},
    'gabriel': {('uriel'): 'baal zebul', ('michael', 'uriel', 'raphael'): 'metatron'},
    'ganesha': {('kaiwan', 'neko shogun'): 'garuda', ('garuda', 'neko shogun'): 'kartikeya'},
    'ganga': {('quetzalcoatl'): 'kaiwan', ('parvati', 'apsaras'): 'kikuri hime', ('sarasvati', 'apsaras'): 'parvati'},
    'garuda': {('ganesha', 'neko shogun'): 'kartikeya', ('horus', 'suzaku', 'yatagarasu', 'gurr'): 'sandalphon'},
    'genbu': {('titan'): 'dionysus', ('byakko', 'suzaku', 'seiryuu'): 'kohryu', ('ares'): 'loa', ('orobas'): 'samael'},
    'ghoul': {('samael', 'loa'): 'mot', ('alice', 'mot', 'samael', 'loa', 'pale rider'): 'thanatos'},
    'girimehkala': {('alice'): 'ganesha', ('orpheus'): 'empusa'},
    'gurr': {('ara mitama', 'nekomata'): 'anubis', ('forneus', 'angel'): 'anubis', ('seth', 'chernobog'): 'baal zebul', ('rangda', 'taraka', 'vetala'): 'girimehkala', ('garuda', 'horus', 'suzaku', 'yatagarasu'): 'sandalphon', ('lilim', 'pixie'): 'uriel'},
    'hanuman': {('titan', 'rakshasa'): 'narasimha', ('orpheus'): 'take minakata'},
    'hariti': {('lilith'): 'cybele', ('orpheus'): 'clotho'},
    'hecatoncheires': {('ubelluris', 'inugami'): 'hell biker', ('ubelluris', 'take minakata'): 'hell biker'},
    'helel': {('beelzebub', 'satan', 'abaddon', 'samael'): 'lucifer', ('messiah', 'metatron', 'chi you', 'asura', 'thanatos'): 'orpheus telos'},
    'hell biker': {('orpheus'): 'orobas', ('pixie'): 'mothman'},
    'high pixie': {('unicorn'): 'apsaras', ('sarasvati', 'high pixie'): 'ganga', ('parvati', 'sarasvati'): 'kikuri hime'},
    'hokuto seikun': {('orpheus'): 'lamia', ('apsaras'): 'oumitsunu'},
    'horus': {('vishnu', 'suparna', 'jatayu', 'quetzalcoatl', 'yatagarasu'): 'asura', ('thanatos', 'norn'): 'chi you', ('garuda', 'suzaku', 'yatagarasu', 'gurr'): 'sandalphon', ('jatayu', 'quetzalcoatl'): 'suparna', ('suparna', 'yatagarasu'): 'vishnu'},
    'hua po': {('virtue'): 'flauros', ('take mikazuchi'): 'genbu', ('sati', 'nekomata'): 'orobas', ('pyro jack', 'nekomata'): 'sati'},
    'incubus': {('baal zebul', 'abaddon', 'lilith', 'pazuzu', 'succubus'): 'beelzebub', ('taraka', 'seiryuu'): 'bishamonten', ('succubus', 'vetala', 'lilim'): 'lilith', ('attis', 'kumbhanda', 'pazuzu', 'mot'): 'mara', ('succubus', 'lilim'): 'pazuzu', ('vetala', 'mokoi'): 'succubus'},
    'inugami': {('ubelluris', 'vasuki', 'orthrus', 'take minakata'): 'attis', ('ara mitama'): 'fortuna', ('jack frost', 'alp'): 'mithra', ('mokoi', 'pyro jack'): 'vetala', ('nigi mitama', 'unicorn'): 'yamatano orochi'},
    'jack frost': {('king frost', 'queen mab', 'pyro jack'): 'black frost', ('inugami', 'alp'): 'mithra', ('angel', 'orpheus'): 'mokoi', ('alp'): 'oberon', ('apsaras', 'pixie'): 'pyro jack'},
    'jatayu': {('vishnu', 'suparna', 'horus', 'quetzalcoatl', 'yatagarasu'): 'asura', ('hokuto seikun'): 'byakko', ('high pixie'): 'mothman', ('horus', 'quetzalcoatl'): 'suparna'},
    'jikokuten': {('titan', 'valkyrie'): 'hanuman', ('bishamonten', 'koumokuten', 'zouchouten'): 'masakado'},
    'kaiwan': {('nandi', 'neko shogun'): 'ganesha', ('ganesha', 'neko shogun'): 'garuda'},
    'kali': {('decarabia', 'dionysus'): 'horus', ('narasimha', 'valkyrie'): 'siegfried'},
    'kartikeya': {('orpheus'): 'uriel', ('pixie'): 'thoth'},
    'kikuri hime': {('okuninushi', 'take minakata', 'omoikane'): 'arahabaki', ('parvati', 'apsaras'): 'scathach'},
    'king frost': {('kingu', 'take mikazuchi'): 'barong', ('queen mab', 'pyro jack', 'jack frost'): 'black frost', ('queen mab', 'pale rider'): 'cu chulainn', ('take mikazuchi', 'forneus'): 'raja naga', ('sati'): 'seiryuu'},
    'kingu': {('raja naga', 'take mikazuchi'): 'barong', ('king frost', 'take mikazuchi'): 'barong', ('barong', 'forneus'): 'odin'},
    'kohryu': {('orpheus'): 'taraka', ('apsaras'): 'nata taishi'},
    'koumokuten': {('vasuki', 'seiryuu'): 'jatayu', ('bishamonten', 'jikokuten', 'zouchouten'): 'masakado', ('nata taishi', 'ara mitama'): 'thor'},
    'kumbhanda': {('attis', 'pazuzu', 'mot', 'incubus'): 'mara', ('chernobog', 'atropos'): 'seiten taisei'},
    'kurama tengu': {('nebiros', 'yomotsu shikome'): 'kumbhanda', ('orpheus'): 'sarasvati'},
    'kusi mitama': {('saki mitama', 'mithra', 'nigi mitama', 'ara mitama'): 'daisoujou', ('clotho', 'fortuna'): 'lachesis'},
    'lachesis': {('clotho', 'fortuna'): 'atropos', ('atropos', 'clotho'): 'norn'},
    'laksmi': {('orpheus'): 'clotho', ('apsaras'): 'saki mitama'},
    'lamia': {('high pixie'): 'jikokuten', ('take minakata'): 'kusi mitama', ('vetala'): 'loa', ('mothman', 'yomotsu shikome'): 'taraka'},
    'leanan sidhe': {('nandi'): 'okuninushi', ('orpheus'): 'empusa'},
    'legion': {('ose', 'slime'): 'decarabia', ('pale rider'): 'jikokuten', ('slime'): 'orpheus', ('narcissus'): 'sarasvati', ('loki', 'decabaria', 'ose', 'black frost', 'orpheus'): 'susano o'},
    'lilim': {('nata taishi', 'narcissus', 'pixie'): 'alice', ('pixie', 'orpheus'): 'eligor', ('apsaras', 'orpheus'): 'eligor', ('succubus', 'incubus', 'vetala'): 'lilith', ('angel', 'pixie'): 'neko shogun', ('gurr', 'pixie'): 'uriel', ('pixie'): 'valkyrie'},
    'lilith': {('baal zebul', 'abaddon', 'pazuzu', 'succubus', 'incubus'): 'beelzebub'},
    'loa': {('setanta', 'empusa'): 'cu chulainn', ('samael', 'ghoul'): 'mot', ('alice', 'mot', 'samael', 'pale rider', 'ghoul'): 'thanatos'},
    'loki': {('decabaria', 'ose', 'black frost', 'legion', 'orpheus'): 'susano o'},
    'lucifer': {('orpheus'): 'kaiwan', ('angel'): 'uriel'},
    'mara': {('orpheus'): 'dionysus', ('alp'): 'kaiwan'},
    'masakado': {('trumpeter'): 'ananta', ('pixie'): 'nandi'},
    'melchizedek': {('angel'): 'virtue', ('ara mitama'): 'orobas'},
    'messiah': {('helel', 'metatron', 'chi you', 'asura', 'thanatos'): 'orpheus telos'},
    'metatron': {('messiah', 'helel', 'chi you', 'asura', 'thanatos'): 'orpheus telos'},
    'michael': {('seiten taisei'): 'ananta', ('gabriel', 'uriel', 'raphael'): 'metatron', ('anubis'): 'trumpeter'},
    'mithra': {('saki mitama', 'kusi mitama', 'nigi mitama', 'ara mitama'): 'daisoujou', ('pyro jack'): 'pale rider'},
    'mokoi': {('rakshasa'): 'empusa', ('ares', 'naga'): 'ose', ('succubus', 'incubus'): 'pazuzu', ('oberon', 'slime'): 'setanta', ('incubus', 'vetala'): 'succubus', ('pyro jack', 'inugami'): 'vetala'},
    'mot': {('attis', 'kumbhanda', 'pazuzu', 'incubus'): 'mara', ('alice', 'samael', 'loa', 'pale rider', 'ghoul'): 'thanatos'},
    'mother harlot': {('angel'): 'kingu', ('ara mitama'): 'succubus'},
    'mothman': {('lamia', 'yomotsu shikome'): 'taraka', ('lamia', 'naga'): 'taraka'},
    'naga': {('nebiros', 'kuruma tengu'): 'kumbhanda', ('kurama tengu', 'taraka'): 'nebiros', ('ares', 'mokoi'): 'ose', ('oberon'): 'titan'},
    'nandi': {('kaiwan', 'neko shogun'): 'ganesha', ('leanan sidhe'): 'okuninushi'},
    'narasimha': {('kurama tengu'): 'atropos', ('decarabia'): 'hecatoncheires', ('hanuman', 'valkyrie'): 'kali', ('hanuman', 'rakshasa'): 'kali', ('kali', 'valkyrie'): 'siegfried'},
    'narcissus': {('nata taishi', 'lilim', 'pixie'): 'alice', ('tam lin', 'pixie'): 'queen mab', ('tam lin', 'alp'): 'queen mab', ('queen mab', 'pixie'): 'saki mitama', ('legion'): 'sarasvati', ('saki mitama', 'tam lin'): 'titania'},
    'nata taishi': {('naricssus', 'lilim', 'pixie'): 'alice', ('take minakata'): 'clotho', ('oumitsunu', 'ara mitama'): 'koumokuten', ('koumokuten', 'ara mitama'): 'thor'},
    'nebiros': {('kurama tengu', 'yomotsu shikome'): 'kumbhanda', ('kingu'): 'koumokuten'},
    'neko shogun': {('kaiwan', 'nandi'): 'ganesha', ('ganesha', 'kaiwan'): 'garuda', ('garuda', 'neko shogun'): 'kartikeya', ('orpheus'): 'uriel'},
    'nekomata': {('apsaras'): 'alp', ('pixie'): 'forneus', ('angel', 'pixie'): 'gurr', ('ara mitama'): 'lilim', ('forneus'): 'nigi mitama', ('orpheus'): 'omoikane', ('hua po', 'pyro jack'): 'sati', ('rangda', 'orobas'): 'surt', ('ara mitama', 'orpheus'): 'yatagarasu'},
    'nidhoggr': {('jatayu'): 'gabriel', ('abaddon', 'attis'): 'satan'},
    'nigi mitama': {('saki mitama', 'kusi mitama', 'mithra', 'ara mitama'): 'daisoujou', ('apsaras'): 'leanan sidhe', ('inugami', 'ara mitama'): 'narcissus', ('okuninushi', 'seiryuu'): 'suzaku', ('unicorn', 'inugami'): 'yamatano orochi', ('byakko', 'suzaku'): 'yurlungur'},
    'norn': {('scathach', 'uriel'): 'chi you', ('thanatos', 'horus'): 'chi you'},
    'oberon': {('berith'): 'ares', ('raja naga', 'king frost'): 'kingu', ('ares'): 'lamia', ('mokoi', 'slime'): 'setanta', ('naga'): 'titan'},
    'odin': {('quetzalcoatl'): 'laksmi', ('nekomata'): 'seiryuu'},
    'okuninushi': {('kikuri hime', 'take minakata', 'omoikane'): 'arahabaki', ('seiryuu', 'nigi mitama'): 'suzaku'},
    'omoikane': {('ara mitama'): 'archangel', ('kikuri hime', 'okuninushi', 'take minakata'): 'arahabaki', ('inugami', 'ara mitama'): 'high pixie', ('alp', 'apsaras'): 'naga', ('forneus', 'angel'): 'principality', ('yomotsu shikome', 'ara mitama'): 'rakshasa', ('unicorn', 'chimera'): 'shiisaa', ('flauros', 'shiisaa'): 'thoth', ('orpheus'): 'yomotsu shikome', ('ara mitama', 'pixie'): 'zouchouten'},
    'orobas': {('taraka', 'seiryuu'): 'bishamonten', ('sati', 'nekomata'): 'rangda', ('sati', 'jack frost'): 'rangda', ('genbu'): 'samael', ('rangda', 'nekomata'): 'surt'},
    'orpheus': {('ose', 'black frost'): 'decarabia', ('lilim', 'pixie'): 'eligor', ('thanatos',): 'messiah', ('pixie', 'ara mitama'): 'oberon', ('loki', 'decabaria', 'ose', 'black frost', 'legion'): 'susano o', ('alp',): 'unicorn', ('neko shogun',): 'uriel', ('ara mitama', 'nekomata'): 'yatagarasu', ('omoikane',): 'yomotsu shikome'},
    'orpheus telos': {('orpheus'): 'ose', ('pixie'): 'parvati'},
    'orthrus': {('ubelluris', 'vasuki', 'take minakata', 'inugami'): 'attis', ('vetala'): 'dionysus', ('hua po'): 'incubus', ('vasuki', 'take minakata'): 'ubelluris'},
    'ose': {('legion', 'slime'): 'decarabia', ('black frost', 'orpheus'): 'decarabia', ('decabaria', 'orpheus'): 'loki', ('decabaria', 'slime'): 'loki', ('loki', 'decabaria', 'black frost', 'legion', 'orpheus'): 'susano o'},
    'oumitsunu': {('orthrus'): 'clotho', ('nata taishi', 'ara mitama'): 'koumokuten', ('zouchouten', 'ara mitama'): 'nata taishi', ('zouchouten', 'chimera'): 'nata taishi'},
    'pale rider': {('king frost', 'queen mab'): 'cu chulainn', ('black frost'): 'hanuman', ('alice', 'mot', 'samael', 'loa', 'ghoul'): 'thanatos'},
    'parvati': {('sarasvati', 'high pixie'): 'kikuri hime', ('kikuri hime', 'apsaras'): 'scathach'},
    'pazuzu': {('baal zebul', 'abaddon', 'lilith', 'succubus', 'incubus'): 'beelzebub', ('attis', 'kumbhanda', 'mot', 'incubus'): 'mara'},
    'pixie': {('nata taishi', 'narcissus', 'lilim'): 'alice', ('yomotsu shikome'): 'archangel', ('raphael', 'titania'): 'cybele', ('lilim', 'orpheus'): 'eligor', ('lilim', 'angel'): 'neko shogun', ('apsaras'): 'nekomata', ('angel', 'apsaras'): 'slime', ('gurr', 'lilim'): 'uriel', ('lilim'): 'valkyrie', ('omoikane', 'ara mitama'): 'zouchouten'},
    'power': {('virtue', 'angel'): 'dominion', ('virtue', 'archangel'): 'dominion', ('principality', 'angel'): 'virtue'},
    'principality': {('archangel'): 'angel', ('berith'): 'ares', ('power', 'angel'): 'virtue'},
    'pyro jack': {('king frost', 'queen mab', 'jack frost'): 'black frost', ('mithra'): 'pale rider', ('hua po', 'nekomata'): 'sati', ('mokoi', 'inugami'): 'vetala'},
    'queen mab': {('king frost', 'pyro jack', 'jack frost'): 'black frost', ('king frost', 'pale rider'): 'cu chulainn', ('narcissus', 'pixie'): 'saki mitama', ('narcissus', 'alp'): 'saki mitama'},
    'quetzalcoatl': {('vishnu', 'suparna', 'horus', 'jatayu', 'quetzalcoatl'): 'asura', ('odin'): 'laksmi'},
    'raja naga': {('kingu', 'forneus'): 'barong', ('king frost', 'forneus'): 'kingu', ('king frost', 'oberon'): 'kingu', ('yatagarasu'): 'yaksini'},
    'rakshasa': {('narasimha', 'hanuman'): 'kali', ('hanuman', 'titan'): 'narasimha', ('yamatano orochi'): 'orthrus'},
    'rangda': {('taraka', 'vetala', 'gurr'): 'girimehkala', ('barong'): 'shiva', ('orobas', 'nekomata'): 'surt'},
    'raphael': {('titania', 'pixie'): 'cybele', ('micahel', 'gabriel', 'uriel'): 'metatron'},
    'saki mitama': {('kusi mitama', 'mithra', 'nigi mitama', 'ara mitama'): 'daisoujou', ('cu chulainn', 'taraka'): 'jatayu', ('titania', 'pixie'): 'raphael', ('narcissus', 'tam lin'): 'titania'},
    'samael': {('helel', 'beelzebub', 'satan', 'abaddon', 'samael'): 'lucifer', ('loa', 'ghoul'): 'mot', ('alice', 'mot', 'loa', 'pale rider', 'ghoul'): 'thanatos'},
    'sandalphon': {('apsaras'): 'nandi', ('omoikane'): 'okuninushi'},
    'sarasvati': {('unicorn'): 'apsaras', ('high pixie', 'apsaras'): 'ganga', ('high pixie', 'unicorn'): 'ganga', ('ganga', 'apsaras'): 'parvati'},
    'satan': {('masakado'): 'atavaka', ('vishnu'): 'helel', ('helel', 'beelzebub', 'abaddon', 'samael'): 'lucifer'},
    'sati': {('power'): 'flauros', ('narcissus'): 'king frost', ('pyro jack', 'jack frost'): 'orobas', ('hua po', 'nekomata'): 'orobas', ('orobas', 'nekomata'): 'rangda', ('king frost'): 'seiryuu'},
    'saturnus': {('raphael'): 'shiva', ('trumpeter'): 'ananta'},
    'scathach': {('uriel', 'norn'): 'chi you', ('orpheus'): 'dominion'},
    'seiryuu': {('taraka', 'orobas'): 'bishamonten', ('taraka', 'incubus'): 'bishamonten', ('byakko', 'suzaku', 'genbu'): 'kohryu', ('okuninushi', 'nigi mitama'): 'suzaku'},
    'seiten taisei': {('anubis'): 'nidhoggr', ('orpheus'): 'dionysus'},
    'setanta': {('ganesha', 'kaiwan'): 'neko shogun', ('shiisaa', 'take mikazuchi'): 'quetzalcoatl'},
    'seth': {('chernobog', 'gurr'): 'baal zebul', ('scathach'): 'kartikeya'},
    'shiisaa': {('setanta', 'take mikazuchi'): 'quetzalcoatl', ('flauros', 'omoikane'): 'thoth'},
    'shiva': {('omoikane'): 'suzaku', ('nigi mitama'): 'pazuzu'},
    'siegfried': {('orpheus'): 'vasuki', ('angel'): 'seiryuu'},
    'skadi': {('mother harlot', 'yaksini'): 'alilat', ('nekomata'): 'ubelluris'},
    'slime': {('ose', 'legion'): 'decarabia', ('chimera', 'alp'): 'narcissus', ('legion'): 'orpheus', ('mokoi', 'oberon'): 'setanta'},
    'succubus': {('baal zebul', 'abaddon', 'lilith', 'pazuzu', 'incubus'): 'beelzebub', ('incubus', 'vetala', 'lilim'): 'lilith', ('incubus', 'mokoi'): 'pazuzu'},
    'suparna': {('vishnu', 'horus', 'jatayu', 'quetzalcoatl', 'yatagarasu'): 'asura', ('horus', 'yatagarasu'): 'vishnu'},
    'surt': {('thor'): 'abaddon', ('pixie'): 'king frost'},
    'susano o': {('orpheus'): 'legion', ('angel'): 'titania'},
    'suzaku': {('narasimha'): 'chernobog', ('byakko', 'seiryuu', 'genbu'): 'kohryu', ('garuda', 'horus', 'yatagarasu', 'gurr'): 'sandalphon', ('byakko', 'nigi mitama'): 'yurlungur'},
    'take mikazuchi': {('kingu', 'king frost'): 'barong', ('power'): 'incubus', ('setanta', 'shiisaa'): 'quetzalcoatl', ('king frost', 'forneus'): 'raja naga'},
    'take minakata': {('kikuri hime', 'okuninushi', 'omoikane'): 'arahabaki', ('ubelluris', 'vasuki', 'orthrus', 'inugami'): 'attis', ('vasuki', 'orthrus'): 'ubelluris'},
    'tam lin': {('alp'): 'pixie', ('zouchouten', 'chimera'): 'power', ('narcissus', 'pixie'): 'queen mab', ('saki mitama', 'narcissus'): 'titania'},
    'taraka': {('seiryuu', 'orobas'): 'bishamonten', ('seiryuu', 'incubus'): 'bishamonten', ('rangda', 'vetala', 'gurr'): 'girimehkala', ('kurama tengu', 'yomotsu shikome'): 'nebiros'},
    'thanatos': {('horus', 'norn'): 'chi you', ('orpheus'): 'messiah', ('messiah', 'helel', 'metatron', 'chi you', 'asura'): 'orpheus telos'},
    'thor': {('nebiros'): 'byakko', ('orpheus'): 'king frost'},
    'thoth': {('flauros', 'omoikane'): 'hokuto seikun', ('orpheus'): 'lamia'},
    'throne': {('mot'): 'chernobog', ('dominion', 'angel'): 'melchizedek'},
    'titan': {('jikokuten', 'valkyrie'): 'hanuman', ('vetala'): 'kusi mitama', ('sarasvati'): 'mothman', ('black frost'): 'vasuki'},
    'titania': {('raphael', 'pixie'): 'cybele', ('seth'): 'hariti', ('saki mitama'): 'raphael', ('saki mitama', 'alp'): 'raphael'},
    'trumpeter': {('satan'): 'michael', ('ananta'): 'saturnus'},
    'ubelluris': {('vasuki', 'orthrus', 'take minakata', 'inugami'): 'attis', ('vasuki', 'inugami'): 'hecatoncheires'},
    'unicorn': {('sarasvati', 'high pixie'): 'ganga', ('inugami', 'chimera'): 'hua po', ('forneus', 'ara mitama'): 'legion', ('ganga', 'apsaras'): 'parvati', ('chimera', 'omoikane'): 'shiisaa', ('nigi mitama', 'inugami'): 'yamatano orochi'},
    'uriel': {('scathach', 'norn'): 'chi you', ('michael', 'gabriel', 'rapahel'): 'metatron'},
    'valkyrie': {('alp'): 'berith', ('jikokuten', 'titan'): 'hanuman', ('hanuman', 'jikokuten'): 'narasimha', ('chimera'): 'principality', ('kali', 'narasimha'): 'siegfried'},
    'vasuki': {('ubelluris', 'orthrus', 'take minakata', 'inugami'): 'attis', ('ubelluris', 'inugami'): 'hecatoncheires', ('orthrus', 'take minakata'): 'ubelluris'},
    'vetala': {('hua po'): 'genbu', ('rangda', 'taraka', 'gurr'): 'girimehkala', ('succubus', 'incubus', 'lilim'): 'lilith', ('incubus', 'mokoi'): 'succubus'},
    'virtue': {('power', 'angel'): 'dominion', ('power', 'archangel'): 'dominion', ('dominion', 'angel'): 'throne'},
    'vishnu': {('suparna', 'horus', 'jatayu', 'quetzalcoatl', 'yatagarasu'): 'asura', ('horus'): 'suparna'},
    'yaksini': {('orpheus'): 'kusi mitama', ('nekomata'): 'orthrus'},
    'yamatano orochi': {('loa', 'pale rider'): 'cu chulainn', ('rakshasa'): 'orthrus', ('chernobog', 'dionysus'): 'seth'},
    'yatagarasu': {('sarasvati'): 'nandi', ('garuda', 'horus', 'suzaku', 'gurr'): 'sandalphon', ('suparna', 'horus'): 'vishnu', ('raja naga'): 'yaksini'},
    'yomotsu shikome': {('omoikane'): 'chimera', ('lilim'): 'ghoul', ('inugami', 'pixie'): 'high pixie', ('kurama tengu', 'taraka'): 'nebiros', ('omoikane', 'ara mitama'): 'rakshasa', ('alp', 'apsaras'): 'take minakata'},
    'yurlungur': {('sandalphon'): 'mother harlot', ('jack frost'): 'samael'},
    'zouchouten': {('nata taishi', 'oumitsunu'): 'koumokuten', ('bishamonten', 'koumokuten', 'jikokuten'): 'masakado', ('oumitsunu', 'ara mitama'): 'nata taishi', ('tam lin', 'chimera'): 'power'},

}
