from p3p_arcana import *

p_stats = {
    'abaddon': 4,
    'alice': 0,
    'alilat': 0,
    'alp': 3,
    'ananta': 6,
    'angel': 37,
    'anubis': 6,
    'apsaras': 51,
    'ara mitama': 32,
    'arahabaki': 0,
    'archangel': 8,
    'ares': 30,
    'asura': 1,
    'atavaka': 3,
    'atropos': 0,
    'attis': 0,
    'baal zebul': 1,
    'barong': 1,
    'beelzebub': 0,
    'berith': 4,
    'bishamonten': 2,
    'black frost': 0,
    'byakko': 2,
    'chernobog': 2,
    'chi you': 3,
    'chimera': 7,
    'clotho': 3,
    'cu chulainn': 1,
    'cybele': 4,
    'daisoujou': 0,
    'decarabia': 0,
    'dionysus': 15,
    'dominion': 2,
    'eligor': 10,
    'empusa': 1,
    'flauros': 6,
    'forneus': 24,
    'fortuna': 15,
    'gabriel': 2,
    'ganesha': 1,
    'ganga': 4,
    'garuda': 1,
    'genbu': 11,
    'ghoul': 2,
    'girimehkala': 0,
    'gurr': 16,
    'hanuman': 2,
    'hariti': 1,
    'hecatoncheires': 1,
    'helel': 1,
    'hell biker': 0,
    'high pixie': 1,
    'hokuto seikun': 3,
    'horus': 3,
    'hua po': 6,
    'incubus': 11,
    'inugami': 15,
    'jack frost': 4,
    'jatayu': 2,
    'jikokuten': 8,
    'kaiwan': 11,
    'kali': 0,
    'kartikeya': 0,
    'kikuri hime': 1,
    'king frost': 21,
    'kingu': 0,
    'kohryu': 0,
    'koumokuten': 3,
    'kumbhanda': 1,
    'kurama tengu': 1,
    'kusi mitama': 0,
    'lachesis': 0,
    'laksmi': 3,
    'lamia': 0,
    'leanan sidhe': 8,
    'legion': 12,
    'lilim': 10,
    'lilith': 1,
    'loa': 0,
    'loki': 1,
    'lucifer': 1,
    'mara': 1,
    'masakado': 1,
    'melchizedek': 3,
    'messiah': 1,
    'metatron': 1,
    'michael': 1,
    'mithra': 1,
    'mokoi': 1,
    'mot': 1,
    'mother harlot': 0,
    'mothman': 6,
    'naga': 4,
    'nandi': 9,
    'narasimha': 0,
    'narcissus': 3,
    'nata taishi': 1,
    'nebiros': 2,
    'neko shogun': 3,
    'nekomata': 6,
    'nidhoggr': 0,
    'nigi mitama': 10,
    'norn': 0,
    'oberon': 1,
    'odin': 3,
    'okuninushi': 4,
    'omoikane': 27,
    'orobas': 0,
    'orpheus': 25,
    'orpheus telos': 0,
    'orthrus': 8,
    'ose': 0,
    'oumitsunu': 1,
    'pale rider': 0,
    'parvati': 3,
    'pazuzu': 2,
    'pixie': 47,
    'power': 2,
    'principality': 0,
    'pyro jack': 13,
    'queen mab': 2,
    'quetzalcoatl': 2,
    'raja naga': 0,
    'rakshasa': 2,
    'rangda': 1,
    'raphael': 0,
    'saki mitama': 1,
    'samael': 2,
    'sandalphon': 0,
    'sarasvati': 16,
    'satan': 0,
    'sati': 1,
    'saturnus': 1,
    'scathach': 0,
    'seiryuu': 3,
    'seiten taisei': 0,
    'setanta': 1,
    'seth': 1,
    'shiisaa': 0,
    'shiva': 0,
    'siegfried': 0,
    'skadi': 0,
    'slime': 9,
    'succubus': 1,
    'suparna': 2,
    'surt': 1,
    'susano o': 0,
    'suzaku': 3,
    'take mikazuchi': 0,
    'take minakata': 4,
    'tam lin': 0,
    'taraka': 2,
    'thanatos': 2,
    'thor': 0,
    'thoth': 4,
    'throne': 0,
    'titan': 0,
    'titania': 0,
    'trumpeter': 0,
    'ubelluris': 4,
    'unicorn': 8,
    'uriel': 4,
    'valkyrie': 9,
    'vasuki': 3,
    'vetala': 1,
    'virtue': 0,
    'vishnu': 2,
    'yaksini': 3,
    'yamatano orochi': 2,
    'yatagarasu': 7,
    'yomotsu shikome': 15,
    'yurlungur': 0,
    'zouchouten': 2
}

# most used persona
max_persona = max(p_stats, key=p_stats.get)
print("The most used persona is", max_persona, "with", p_stats[max_persona], "uses.")

# most used arcana
arcana_count = {}
for p in p_stats:
    if persona_stats[p][1] not in arcana_count.keys() and p_stats[p] != 0:
        arcana_count[persona_stats[p][1]] = 1
    if p_stats[p] != 0:
        arcana_count[persona_stats[p][1]] += 1
max_arcana = max(arcana_count, key=arcana_count.get)
print("The most used arcana is", max_arcana, "with", arcana_count[max_arcana], "uses.")

# personas with 0 uses
zero_nj = []
for p in p_stats:
    if p_stats[p] == 0:
        zero_nj.append(p)
print("list of personas used zero times: ", zero_nj)
